In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv(
    r"C:\Users\abera\Downloads\cleaned_telco_churn.csv"
)

df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
print(df.shape)

df.info()

(7021, 20)
<class 'pandas.DataFrame'>
RangeIndex: 7021 entries, 0 to 7020
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7021 non-null   str
 1   SeniorCitizen     7021 non-null   int64
 2   Partner           7021 non-null   str
 3   Dependents        7021 non-null   str
 4   tenure            7021 non-null   int64
 5   PhoneService      7021 non-null   str
 6   MultipleLines     7021 non-null   str
 7   InternetService   7021 non-null   str
 8   OnlineSecurity    7021 non-null   str
 9   OnlineBackup      7021 non-null   str
 10  DeviceProtection  7021 non-null   str
 11  TechSupport       7021 non-null   str
 12  StreamingTV       7021 non-null   str
 13  StreamingMovies   7021 non-null   str
 14  Contract          7021 non-null   str
 15  PaperlessBilling  7021 non-null   str
 16  PaymentMethod     7021 non-null   str
 17  MonthlyCharges    7021 non-null   float64
 18  TotalCharges      7010 non-null   float64
 19  Churn             7021 non-null   str
dtypes: float64(2), int64(2), str(16)
memory usage: 1.7 MB

In [4]:
df.isnull().sum()

gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [5]:
categorical_columns = df.select_dtypes(
    include='object'
).columns

categorical_columns

Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'Churn'],
      dtype='str')

In [6]:
le = LabelEncoder()

for col in categorical_columns:

    df[col] = le.fit_transform(
        df[col]
    )

print("Label Encoding Completed")

Label Encoding Completed

In [7]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.85,0
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1889.50,0
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,108.15,1
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1840.75,0
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.65,1

In [12]:
df['Tenure_Group'] = pd.cut(
    df['tenure'],
    bins=[0, 12, 24, 48, 72],
    labels=['0-12', '13-24', '25-48', '49-72'],
    include_lowest=True
)

print("Tenure Group Feature Created Successfully")

df[['tenure', 'Tenure_Group']].head(10)

Tenure Group Feature Created Successfully

   tenure Tenure_Group
0       1         0-12
1      34        25-48
2       2         0-12
3      45        25-48
4       2         0-12
5       8         0-12
6      22        13-24
7      10         0-12
8      28        25-48
9      62        49-72

In [13]:
df['MonthlyCharges_Group'] = pd.cut(
    df['MonthlyCharges'],
    bins=3,
    labels=['Low', 'Medium', 'High']
)

print("Monthly Charges Group Created Successfully")

df[['MonthlyCharges',
    'MonthlyCharges_Group']].head(10)

Monthly Charges Group Created Successfully

   MonthlyCharges MonthlyCharges_Group
0           29.85                  Low
1           56.95               Medium
2           53.85               Medium
3           42.30                  Low
4           70.70               Medium
5           99.65                 High
6           89.10                 High
7           29.75                  Low
8          104.80                 High
9           56.15               Medium

In [14]:
df['TotalCharges_Group'] = pd.cut(
    df['TotalCharges'],
    bins=3,
    labels=['Low', 'Medium', 'High']
)

print("Total Charges Group Created Successfully")

df[['TotalCharges',
    'TotalCharges_Group']].head(10)

Total Charges Group Created Successfully

   TotalCharges TotalCharges_Group
0         29.85                Low
1       1889.50                Low
2        108.15                Low
3       1840.75                Low
4        151.65                Low
5        820.50                Low
6       1949.40                Low
7        301.90                Low
8       3046.05             Medium
9       3487.95             Medium

In [15]:
df[['Tenure_Group',
    'MonthlyCharges_Group',
    'TotalCharges_Group']].head()

  Tenure_Group MonthlyCharges_Group TotalCharges_Group
0         0-12                  Low                Low
1        25-48               Medium                Low
2         0-12               Medium                Low
3        25-48                  Low                Low
4         0-12               Medium                Low

In [17]:
df['Avg_Monthly_Spend'] = (
    df['TotalCharges'] /
    (df['tenure'] + 1)
)

print("Average Monthly Spend Feature Created")

df[['Avg_Monthly_Spend']].head()

Average Monthly Spend Feature Created

   Avg_Monthly_Spend
0          14.925000
1          53.985714
2          36.050000
3          40.016304
4          50.550000

In [18]:
df['Customer_Lifetime_Value'] = (
    df['MonthlyCharges'] *
    df['tenure']
)

print("Customer Lifetime Value Feature Created")

df[['Customer_Lifetime_Value']].head()

Customer Lifetime Value Feature Created

   Customer_Lifetime_Value
0                    29.85
1                  1936.30
2                   107.70
3                  1903.50
4                   141.40

In [19]:
df['Has_Internet'] = np.where(
    df['InternetService'] > 0,
    1,
    0
)

print("Has Internet Feature Created")

df[['Has_Internet']].head()

Has Internet Feature Created

   Has_Internet
0             0
1             0
2             0
3             0
4             1

In [20]:
df['Has_Security'] = np.where(
    df['OnlineSecurity'] > 0,
    1,
    0
)

print("Has Security Feature Created")

df[['Has_Security']].head()

Has Security Feature Created

   Has_Security
0             0
1             1
2             1
3             1
4             0

In [21]:
df['Streaming_User'] = np.where(
    (
        df['StreamingTV'] > 0
    ) |
    (
        df['StreamingMovies'] > 0
    ),
    1,
    0
)

print("Streaming User Feature Created")

df[['Streaming_User']].head()

Streaming User Feature Created

   Streaming_User
0               0
1               0
2               0
3               0
4               0

In [22]:
df['Support_User'] = np.where(
    (
        df['TechSupport'] > 0
    ) |
    (
        df['DeviceProtection'] > 0
    ),
    1,
    0
)

print("Support User Feature Created")

df[['Support_User']].head()

Support User Feature Created

   Support_User
0             0
1             1
2             0
3             1
4             0

In [23]:
df['Service_Count'] = (

    df['PhoneService'] +

    df['MultipleLines'] +

    df['OnlineSecurity'] +

    df['OnlineBackup'] +

    df['DeviceProtection'] +

    df['TechSupport'] +

    df['StreamingTV'] +

    df['StreamingMovies']

)

print("Service Count Feature Created")

df[['Service_Count']].head()

Service Count Feature Created

   Service_Count
0              3
1              5
2              5
3              7
4              1

In [24]:
print(df[['Service_Count']].head(10))

   Service_Count
0              3
1              5
2              5
3              7
4              1
5              9
6              7
7              3
8             11
9              5

In [25]:
scaler = MinMaxScaler()

scale_columns = [

    'tenure',

    'MonthlyCharges',

    'TotalCharges',

    'Avg_Monthly_Spend',

    'Customer_Lifetime_Value',

    'Service_Count'

]

df[scale_columns] = scaler.fit_transform(
    df[scale_columns]
)

print("Feature Scaling Completed")

Feature Scaling Completed

In [26]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,Tenure_Group,TotalCharges_Group,MonthlyCharges_Group,Avg_Monthly_Spend,Customer_Lifetime_Value,Has_Internet,Has_Security,Streaming_User,Support_User,Service_Count
0,0,0,1,0,0.013889,0,1,0,0,2,...,0-12,Low,Low,0.052298,0.003491,0,0,0,0,0.142857
1,1,0,0,0,0.472222,1,0,0,2,0,...,25-48,Low,Medium,0.408086,0.226468,0,1,0,1,0.285714
2,1,0,0,0,0.027778,1,0,0,2,2,...,0-12,Low,Medium,0.244717,0.012596,0,1,0,0,0.285714
3,1,0,0,0,0.625000,0,1,0,2,0,...,25-48,Low,Low,0.280845,0.222632,0,1,0,1,0.428571
4,0,0,0,0,0.027778,1,0,1,0,0,...,0-12,Low,Medium,0.376792,0.016538,1,0,0,0,0.000000

In [27]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
gender,7021.0,0.504344,0.500017,0.0,0.000000,1.000000,1.000000,1.0
SeniorCitizen,7021.0,0.162512,0.368947,0.0,0.000000,0.000000,0.000000,1.0
Partner,7021.0,0.484546,0.499797,0.0,0.000000,0.000000,1.000000,1.0
Dependents,7021.0,0.300527,0.458520,0.0,0.000000,0.000000,1.000000,1.0
tenure,7021.0,0.450965,0.340763,0.0,0.125000,0.402778,0.763889,1.0
PhoneService,7021.0,0.902863,0.296166,0.0,1.000000,1.000000,1.000000,1.0
MultipleLines,7021.0,0.943455,0.948575,0.0,0.000000,1.000000,2.000000,2.0
InternetService,7021.0,0.870816,0.737076,0.0,0.000000,1.000000,1.000000,2.0
OnlineSecurity,7021.0,0.790486,0.860730,0.0,0.000000,1.000000,2.000000,2.0
OnlineBackup,7021.0,0.907278,0.880999,0.0,0.000000,1.000000,2.000000,2.0
DeviceProtection,7021.0,0.905284,0.880787,0.0,0.000000,1.000000,2.000000,2.0
TechSupport,7021.0,0.797607,0.862432,0.0,0.000000,1.000000,2.000000,2.0
StreamingTV,7021.0,0.986469,0.885762,0.0,0.000000,1.000000,2.000000,2.0
StreamingMovies,7021.0,0.993591,0.885842,0.0,0.000000,1.000000,2.000000,2.0
Contract,7021.0,0.692636,0.834163,0.0,0.000000,0.000000,1.000000,2.0
PaperlessBilling,7021.0,0.592651,0.491376,0.0,0.000000,1.000000,1.000000,1.0
PaymentMethod,7021.0,1.570716,1.067530,0.0,1.000000,2.000000,2.000000,3.0
MonthlyCharges,7021.0,0.463700,0.299194,0.0,0.174129,0.518905,0.712935,1.0
TotalCharges,7010.0,0.262122,0.261576,0.0,0.044947,0.159829,0.437230,1.0
Churn,7021.0,0.264492,0.441094,0.0,0.000000,0.000000,1.000000,1.0
Avg_Monthly_Spend,7010.0,0.455691,0.277530,0.0,0.156845,0.474083,0.689822,1.0
Customer_Lifetime_Value,7021.0,0.267440,0.264887,0.0,0.046784,0.163415,0.443673,1.0
Has_Internet,7021.0,0.655462,0.475251,0.0,0.000000,1.000000,1.000000,1.0
Has_Security,7021.0,0.502920,0.500027,0.0,0.000000,1.000000,1.000000,1.0
Streaming_User,7021.0,0.713716,0.452056,0.0,0.000000,1.000000,1.000000,1.0
Support_User,7021.0,0.679248,0.466799,0.0,0.000000,1.000000,1.000000,1.0
Service_Count,7021.0,0.444788,0.239171,0.0,0.285714,0.428571,0.571429,1.0

In [28]:
df.to_csv(
    r"C:\Users\abera\Downloads\featured_telco_churn.csv",
    index=False
)

print("Feature Engineered Dataset Saved Successfully")

Feature Engineered Dataset Saved Successfully